8617
1674
Traceback (most recent call last):
  File "train_two_record_model.py", line 339, in <module>
    metrics_train_final = main(args, experiment=experiment)
  File "train_two_record_model.py", line 130, in main
    train_loader = DataLoader(train_dataset, batch_size=args.batch_size, drop_last=True, collate_fn=PadCollate(ch=ch, graph_type=args.graphtype), num_workers=args.workers, shuffle=True)
  File "/root/code/LogicMD/utils/data_utils.py", line 40, in __init__
    self.tokenizer = AutoTokenizer.from_pretrained('//data/sunhao/bert/bert-base-uncased')
  File "/root/miniconda3/envs/mocheg/lib/python3.8/site-packages/transformers/models/auto/tokenization_auto.py", line 677, in from_pretrained
    tokenizer_config = get_tokenizer_config(pretrained_model_name_or_path, **kwargs)
  File "/root/miniconda3/envs/mocheg/lib/python3.8/site-packages/transformers/models/auto/tokenization_auto.py", line 510, in get_tokenizer_config
    resolved_config_file = cached_file(
  File "/root/miniconda3/envs/mocheg/lib/python3.8/site-packages/transformers/utils/hub.py", line 428, in cached_file
    resolved_file = hf_hub_download(
  File "/root/miniconda3/envs/mocheg/lib/python3.8/site-packages/huggingface_hub/utils/_validators.py", line 110, in _inner_fn
    validate_repo_id(arg_value)
  File "/root/miniconda3/envs/mocheg/lib/python3.8/site-packages/huggingface_hub/utils/_validators.py", line 158, in validate_repo_id
    raise HFValidationError(
huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': '//data/sunhao/bert/bert-base-uncased'. Use `repo_type` argument if needed.
